Добавляет fetch
htmlacademy-javascript/1701403-keksobooking-23 pull request #10
Opened 2021-07-03 14:24 UTC by alisabox

2021-07-05 10:50 UTC, Spearance requested changes

2021-07-05 10:50 UTC, Spearance commented on js/alert.js
> +  document.addEventListener('keydown', (evt) => {
у тебя вовремя не удаляется событие, поэтому каждый раз как ты будешь что-то отправлять на сервер, будет навешиваться новое

2021-07-05 19:06 UTC, Spearance requested changes

2021-07-05 19:06 UTC, Spearance commented on js/alert.js
> +  document.removeEventListener('keydown', closeMessageHandler(evt));
тут не нужен вызов функции
document.removeEventListener('keydown', closeMessageHandler);

2021-07-05 19:06 UTC, Spearance commented on js/alert.js
> +  document.addEventListener('keydown', (evt) => {
а вот тут нужно указать функцию и она должна быть идентичной той что удаляется иначе не удалится:
document.addEventListener('keydown', closeMessageHandler);

2021-07-06 00:37 UTC, alisabox commented
Все, теперь разобралась, работает.

2021-07-06 06:35 UTC, Spearance commented on js/alert.js
> +      errorMessage.remove();
в обоих случаях и с successMessage и errorMessage будет true первый раз и будут удалены, но второй раз уже не сработает

2021-07-06 14:04 UTC, merged